### ISSUE TITLE
backup tables only

### ISSUE THREAD

**Issue by Trapulo** [TheByteStuff/AzureTableBackupRestore#2]
How may I setup config to perform only a backup of a Table to a local file?

It seems that it fails if I don't provide every option in appsettings..

thanks

**Comment by TheByteStuff** [comment]
Good catch, sorry about that.  I hadn't tested with empty config options.   I'll keep this open as a reminder to tweak the code to allow for missing parms from the file.  In the meantime here's an example which will create a backup on a local file, replace the info between the "<<>>" for your environment.  Anything in empty quotes can remain in empty quotes.  


```
{
  "ConnectionStrings": {
    "AzureStorageConfigConnection": "<<endpointinfohere>>",
    "AzureStorageDestinationConfigConnection": "",
    "AzureBlobStorageConfigConnection": "<<endpointinfohere>>"
  },
  "Command": "backup",
  "Target": "ToFile",
  "TableName": "<<TableName>>",
  "DestinationTableName": "",
  "OriginalTableName": "",
  "BlobRoot": "",
  "BlobFileName": "",
  "WorkingDirectory": "",
  "OutFileDirectory": "<<outputdirectory>>",
  "RestoreFileNamePath": "",
  "Compress": "",
  "Validate": "",
  "RetentionDays": "",
  "TimeoutSeconds": "30",
  "Filters": [],
  "InFilePathName": ""
}
```

**Comment by Trapulo** [comment]
Sorry for long delay: I can confirm that I can backup tables.

I'm also upgraded to .NET 6, I will push ASAP

thanls
